### PR TITLE
updated aurelia version

### PR DESCRIPTION
**Pull request by danice**
hello!
I have contributed to aurelia2-examples with a fast framework example, you can find it here:
https://github.com/aurelia/aurelia2-examples/tree/main/examples/fast-app

I tried to use the aurelia-fast-adapter but it give me an error, caused by this aurelia refactor
https://github.com/aurelia/aurelia/commit/5a11ea0ead1252021a8fc55536456d72972214c2

I have prepared a fix for that... could you merge it and I will try to use in the example?

Thanks!

### CODE REVIEW

**Comment by ben-girardet** [comment]
Thanks for the MR. 
Keep me posted to confirm if this fixes your issue.

**Comment by danice** [comment]
I have tested with a local version of the package and it works... can you update package version in npm repository so I can include it in the example project?  Thanks!

**Comment by danice** [comment]
Yes, i had to updated npm wit ``npm install --global npm``  but here it is (zipped)
[aurelia-fast-adapter-1.0.6.tgz.zip](https://github.com/ben-girardet/aurelia-fast-adapter/files/9820671/aurelia-fast-adapter-1.0.6.tgz.zip)

**Comment by ben-girardet** [comment]
I published a new version `1.0.6`. Hope it works as you expect.

**Pull request merged**
